### ISSUE TITLE
Restart consumer, it locks at libsystem_kernel.dylib`sem_wait

### ISSUE THREAD

**Issue by ghost** [talrasha007/lmdb-queue#3]
I use PM2 start four producers and four consumers, then start status.js to call topic.status() every ms.
If I kill one consumer 2~3 times, (pm2 will restart it), status.js will not print out anything, I use lldb attach the killed consumer, It shows:

Executable module set to "/usr/local/Cellar/node/0.12.7/bin/node".
Architecture set to: x86_64h-apple-macosx.
(lldb) bt
- thread #1: tid = 0xc13a8, 0x00007fff9d2a1642 libsystem_kernel.dylib`sem_wait + 10, name = 'node /Users/zwb/Documents/TalkingData/Code/learn-lmdb-queue/con', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  - frame #0: 0x00007fff9d2a1642 libsystem_kernel.dylib`sem_wait + 10
    frame #1: 0x000000010534a951 lmdb-queue.node`mdb_sem_wait(sem=<unavailable>) + 17 at mdb.c:265
    frame #2: 0x0000000105342e8d lmdb-queue.node`mdb_txn_renew0(txn=0x0000000102015000) + 66 at mdb.c:2533
    frame #3: 0x0000000105343540 lmdb-queue.node`mdb_txn_begin(env=0x0000000101a0c6f0, parent=0x0000000000000003, flags=<unavailable>, ret=0x00007fff5fbf5618) + 950 at mdb.c:2702
    frame #4: 0x0000000105340844 lmdb-queue.node`Topic::Topic(Env*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [inlined] Txn::Txn(env=0x0000000101a0c620, readOnly=false) + 74 at env.h:70
    frame #5: 0x000000010534081f lmdb-queue.node`Topic::Topic(Env_, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [inlined] Txn::Txn(env=0x0000000101a0c620, readOnly=false) at env.h:69
    frame #6: 0x000000010534081f lmdb-queue.node`Topic::Topic(this=0x0000000101a00140, env=0x0000000101a0c620, name=0x00007fff5fbf5708) + 37 at topic.cc:28
    frame #7: 0x000000010534002f lmdb-queue.node`Env::getTopic(this=0x0000000101a0c620, name=0x00007fff5fbf5708) + 83 at env.cc:52
    frame #8: 0x00000001053418c1 lmdb-queue.node`Consumer::Consumer(this=0x0000000101a0c598, root=<unavailable>, topic=<unavailable>, name=0x00007fff5fbf56f0, opt=0x00007fff5fbf5780) + 51 at consumer.cc:6
    frame #9: 0x000000010533fa86 lmdb-queue.node`ConsumerWrap::ConsumerWrap(this=0x0000000101a0c580, path=<unavailable>, topicName=<unavailable>, name=0x0000000101a084d0, opt=<unavailable>) + 170 at module.cc:195
    frame #10: 0x000000010533f46f lmdb-queue.node`ConsumerWrap::ctor(v8::FunctionCallbackInfo<v8::Value> const&) [inlined] ConsumerWrap::ConsumerWrap(this=0x0000000101a0c580, path=0x0000000101a0b790, topicName=0x0000000101a0b7e0, name=0x0000000101a084d0, opt=<unavailable>) + 547 at module.cc:195
    frame #11: 0x000000010533f45c lmdb-queue.node`ConsumerWrap::ctor(args=0x00007fff5fbf57e8) + 528 at module.cc:152
    frame #12: 0x00000001001317ac node`v8::internal::FunctionCallbackArguments::Call(void (_)(v8::FunctionCallbackInfov8::Value const&)) + 160
    frame #13: 0x000000010014e03f node`v8::internal::Builtin_HandleApiCallConstruct(int, v8::internal::Object*_, v8::internal::Isolate_) + 568

**Comment by talrasha007** [comment]
[Commit #b78b48e](https://github.com/talrasha007/lmdb-queue/commit/b78b48eebb7d51f6ccd3c7e042db85d95a561594) should fixed it
